# # Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  deploy:
    # machine:
    #   macos:
    #     xcode: '9.0'
    working_directory: ~/project/website
    docker:
      - image: circleci/node:lts
    environment:
      NETLIFY_AUTH_TOKEN: Xjb13Vkj9ruyzpLbl9zyFV7nFsxA2YEWV8tCZLxiGIg
    steps:
      - checkout
      - run: 
          name: variable_substitution
          command: |
            pwd
            ls
            cd Q1
            echo "No need to build, it is a html page. Now substitute CIRCLE_BUILD_NUM."
            echo $CIRCLE_BUILD_NUM
            sed "s/CIRCLE_BUILD_NUM/$CIRCLE_BUILD_NUM/" index.html > index1.html
            cat index1.html
            ls
            mv index1.html index.html
            ls
      - run:
          name: deploy
          command: |
            cd website
            cat index.html
            yarn run deploy

workflows:
  version: 2
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main